const SUPABASE_URL =
  'PASTE_YOUR_VITE_SUPABASE_URL_HERE';

const SUPABASE_PUBLISHABLE_KEY =
  'PASTE_YOUR_VITE_SUPABASE_PUBLISHABLE_KEY_HERE';

export const supabase =
  window.supabase.createClient(
    SUPABASE_URL,
    SUPABASE_PUBLISHABLE_KEY
  );
